### ISSUE TITLE
Error in Assertion / CodeSandbox

### ISSUE THREAD

**Issue by tbuckley** [tbuckley/evals-pwa#204]
FAIL - Error in javascript assertion: Cannot read properties of undefined (reading 'postMessage') Stack trace: TypeError: Cannot read properties of undefined (reading 'postMessage') at https://evals.tbuckley.com/_app/immutable/chunks/actions.BSUa_JFF.js:807:447 at new Promise (<anonymous>) at https://evals.tbuckley.com/_app/immutable/chunks/actions.BSUa_JFF.js:807:174 at Object.run (https://evals.tbuckley.com/_app/immutable/chunks/actions.BSUa_JFF.js:941:447) at async $h (https://evals.tbuckley.com/_app/immutable/chunks/actions.BSUa_JFF.js:974:31348) at async

@dstoc FYI

**Comment by tbuckley** [comment]
Somehow we are ending up here with codePort being undefined: https://github.com/tbuckley/evals-pwa/blob/main/src/lib/utils/CodeSandbox.ts#L123
