### ISSUE TITLE
Unhandled exception if provider name is invalid

### ISSUE THREAD

**Issue by dstoc** [tbuckley/evals-pwa#98]
```
Uncaught (in promise) Error: Invalid provider id: gemini-1.5-flash-8b-exp-0827
    at na.getRequiredEnvVars (actions.q7okR_Qn.js:3:986)
    at actions.q7okR_Qn.js:4:336
    at g (index.BiIB1rHI.js:1:762)
    at index.BiIB1rHI.js:1:874
    at Object.l [as subscribe] (index.BiIB1rHI.js:1:411)
    at M (scheduler.GmDJAubM.js:1:522)
    at index.BiIB1rHI.js:1:812
    at Array.map (<anonymous>)
    at index.BiIB1rHI.js:1:801
    at Object.l [as subscribe] (index.BiIB1rHI.js:1:411)
```

**Comment by tbuckley** [comment]
![CleanShot 2024-11-13 at 23 26 42@2x](https://github.com/user-attachments/assets/d43ed4c1-23e8-4063-bbc8-dab0ec7e2532)
